global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'model-service'
    static_configs:
      - targets: ['model-service:5000']
    metrics_path: '/metrics'

  - job_name: 'predictive-analytics'
    static_configs:
      - targets: ['predictive-analytics:5000']
    metrics_path: '/metrics'
    
  - job_name: 'model-runners'
    dns_sd_configs:
      - names:
          - 'model-service'
        type: 'A'
        port: 8000
        refresh_interval: 30s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: '${1}'
      - source_labels: [__meta_dns_name]
        target_label: service
        replacement: 'model-runner'
