global:
  scrape_interval: 15s
  evaluation_interval: 15s

# 添加告警规则文件配置
rule_files:
  - "alert_rules.yaml"

# Alertmanager 配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'model-service'
    static_configs:
      - targets: ['model-service:5000']
    metrics_path: '/metrics'

  - job_name: 'predictive-analytics'
    static_configs:
      - targets: ['predictive-analytics:5000']
    metrics_path: '/metrics'
    
  - job_name: 'model-runners'
    dns_sd_configs:
      - names:
          - 'model-service'
        type: 'A'
        port: 8000
        refresh_interval: 30s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        regex: '.*'
        target_label: instance
        replacement: '${1}'
      - source_labels: [__meta_dns_name]
        target_label: service
        replacement: 'model-runner'

  # 添加单独的作业专门用于收集模型资源指标
  - job_name: 'model-metrics'
    static_configs:
      - targets: ['model-service:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'instance_model_.*'
        action: 'keep'

  # 添加Node Exporter作为监控目标，用于收集系统资源使用情况
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: '/metrics'
