global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'model-service'
    static_configs:
      - targets: ['model-service:5000']
    metrics_path: '/metrics'

  - job_name: 'predictive-analytics'
    static_configs:
      - targets: ['predictive-analytics:5000']
    metrics_path: '/metrics'
